import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import QueryProvider from "@/app/components/QueryProvider";
import { Toaster } from "sonner";
import LoadingSpinner from "@/components/LoadingSpinner";
import ClientProviders from "@/app/components/ClientProviders";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pc shop",
  description: "Generated by create next app",
};


export default function RootLayout({

  
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
{
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientProviders>
          <LoadingSpinner>
            <div className="bg-[#030712]">
              <Navbar />
              <main className="py-20 bg-[#030712]">{children}</main>
              <Footer />
            </div>
          </LoadingSpinner>
        </ClientProviders>
      </body>
    </html>

  );
}
