"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import QueryProvider from "@/app/components/QueryProvider";
import { Toaster } from "sonner";
import LoadingSpinner from "@/components/LoadingSpinner";
import ClientProviders from "@/app/components/ClientProviders";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Pc shop",
//   description: "Generated by create next app",
// };

function LayoutContent({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  const hideNavFooter = pathname === "/login" || pathname === "/register";

  return (
    <ClientProviders>
      <LoadingSpinner>
        <div className="min-h-screen bg-[#030712] flex flex-col">
          {!hideNavFooter && <Navbar />}
          <main className="flex-1 bg-[#030712] px-4 sm:px-6 lg:px-8 py-12">{children}</main>
          {!hideNavFooter && <Footer />}
        </div>
      </LoadingSpinner>
    </ClientProviders>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#030712]`}>
        <LayoutContent>{children}</LayoutContent>
      </body>
    </html>
  );
}
